FROM python:3.4
MAINTAINER "DataSystems"

# Copy requirements file in seperately to rest of project.
# This allows docker to cache requirements, and so only changes to
# requirements.txt will trigger a new pip install
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

ADD . /essence-hive
WORKDIR /essence-hive

ENV PYTHONPATH=/essence-hive:$PYTHONPATH
ENV ESSENCE_HIVE_BASE=/essence-hive
